package com.yc.test
import com.sample.DroolFuZhu

rule "chushi1"
    when
        m : DroolFuZhu(startI>=endI)
    then
     	m.setMaxI(m.getStartI());
     	m.setMinI(m.getEndI());
end

rule "chushi2"
    when
        m : DroolFuZhu(startI<endI)
    then
     	m.setMaxI(m.getEndI());
     	m.setMinI(m.getStartI());
end

rule "chushi3"
    when
        m : DroolFuZhu(startJ>=endJ)
    then
     	m.setMaxJ(m.getStartJ());
     	m.setMinJ(m.getEndJ());
end

rule "chushi4"
    when
        m : DroolFuZhu(startJ<endJ)
    then
     	m.setMaxJ(m.getEndJ());
     	m.setMinJ(m.getStartJ());
end

rule "ju1"
    when
        m : DroolFuZhu(name=="車",maxI==minI)
    then
     		for(int j=m.getMinJ()+1;j<m.getMaxJ();j++)
			{
				if(m.getQiZi()[m.getMaxI()][j]!=null)//如果中间有棋子
				{
					m.setCanMove(false);//不可以走棋
					System.out.println("111");
				}
			}
end





